language: ruby
bundler_args: --without debug
rvm:
  - 2.1.0
  - 2.0.0
  - jruby-head
  - ruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx

services:
  - mongodb